In [1]:
from torchvision import datasets
from torch.utils.data import Subset, Dataset

train_dataset = datasets.CIFAR10('/ailab_mat/personal/heo_yunjae/uncertainty-activelearning/domain_divergence/data', download=True)
print(train_dataset[0])

/home/bengio/anaconda3/envs/hyj_spice/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Files already downloaded and verified
(<PIL.Image.Image image mode=RGB size=32x32 at 0x7FF2DECFA700>, 6)


In [4]:
import random

idx = [i for i in range(50000)]
random.shuffle(idx)
print(idx[:10])

[30574, 29302, 5537, 43080, 49286, 41699, 38075, 7640, 5744, 46592]


In [45]:
import pickle

with open('/ailab_mat/personal/heo_yunjae/Parameters/Uncertainty/domian_divergence/seed0/epoch1/lbl_idx.pkl', 'rb') as f:
    lbl_idx = pickle.load(f)
    
with open('/ailab_mat/personal/heo_yunjae/Parameters/Uncertainty/domian_divergence/seed0/epoch1/ulbl_idx.pkl', 'rb') as f:
    ulbl_idx = pickle.load(f)


In [46]:
print(len(lbl_idx))
print(len(ulbl_idx))

print('lbl_idx')
lbl_idx = list(lbl_idx)
box = []
for idx in lbl_idx:
    if lbl_idx.count(idx) > 1:
        # print(idx, lbl_idx.count(idx))
        lbl_idx.remove(idx)
        box.append(idx)
print(len(box))
print(len(lbl_idx))

2000
49000
lbl_idx
0
2000


In [69]:
import torch
import torch.nn.functional as F

device = 'cuda'

temp = torch.tensor([]).to(device)
a = torch.rand([64,2]).to(device)
a = F.softmax(a, 1)
# b = torch.max(a, dim=1)
b = a[:,0]
print(b)
temp = torch.cat((temp,b),dim=0)
print(temp)

tensor([0.5587, 0.6030, 0.5612, 0.6301, 0.3860, 0.6361, 0.3459, 0.4786, 0.3404,
        0.5468, 0.4915, 0.3141, 0.5511, 0.4286, 0.5861, 0.5883, 0.5124, 0.5853,
        0.3891, 0.5621, 0.6328, 0.3745, 0.6507, 0.3814, 0.5324, 0.4749, 0.4305,
        0.5261, 0.5144, 0.6315, 0.4317, 0.4497, 0.3387, 0.7062, 0.3978, 0.7165,
        0.4559, 0.3991, 0.4657, 0.5599, 0.6847, 0.3900, 0.6515, 0.4622, 0.4597,
        0.5955, 0.4800, 0.4763, 0.3708, 0.4901, 0.6303, 0.3826, 0.6199, 0.4665,
        0.4204, 0.5745, 0.4949, 0.4716, 0.5530, 0.6062, 0.6354, 0.5310, 0.4577,
        0.5804], device='cuda:0')
tensor([0.5587, 0.6030, 0.5612, 0.6301, 0.3860, 0.6361, 0.3459, 0.4786, 0.3404,
        0.5468, 0.4915, 0.3141, 0.5511, 0.4286, 0.5861, 0.5883, 0.5124, 0.5853,
        0.3891, 0.5621, 0.6328, 0.3745, 0.6507, 0.3814, 0.5324, 0.4749, 0.4305,
        0.5261, 0.5144, 0.6315, 0.4317, 0.4497, 0.3387, 0.7062, 0.3978, 0.7165,
        0.4559, 0.3991, 0.4657, 0.5599, 0.6847, 0.3900, 0.6515, 0.4622, 0.4597,
      

In [73]:
import enum
import dataset
from torchvision import datasets
from torch.utils.data import DataLoader
import utils
import random

datapath = '/ailab_mat/personal/heo_yunjae/Parameters/Uncertainty/data'
train_dataset = datasets.CIFAR10(datapath, download=True, transform=utils.get_rand_augment('cifar10'))
dataloader = DataLoader(train_dataset, 32)

for (data,label) in dataloader:
    print(label)
    break


Files already downloaded and verified
tensor([6, 9, 9, 4, 1, 1, 2, 7, 8, 3, 4, 7, 7, 2, 9, 9, 9, 3, 2, 6, 4, 3, 6, 6,
        2, 6, 3, 5, 4, 0, 0, 9])


In [145]:
import torch

a = torch.rand([3,2])
b = torch.rand([3,2])

print(a)
print(a[:,0])
print(b)

print(a[:,0]+b[:,0])

tensor([[0.5788, 0.1523],
        [0.8336, 0.9204],
        [0.0550, 0.9702]])
tensor([0.5788, 0.8336, 0.0550])
tensor([[0.7092, 0.2525],
        [0.4949, 0.5697],
        [0.8030, 0.5981]])
tensor([1.2880, 1.3285, 0.8579])
